### ISSUE TITLE
Support for Rails 6

### ISSUE THREAD

**Issue by bbay** [fcheung/asset_symlink#10]
Hello there @fcheung 

I have been running this gem in Rails 6.0.0 without any problems for quite some time but today I found that when updating to Rails 6.0.2.1, asset_symlink seems to lock the dependency to Rails 5 (6.0.0?)

Could you expand the support to Rails 6.* ?

Thanks for this gem by the way! It solves a painful issue with the asset pipeline

**Comment by fcheung** [comment]
Great to hear it has been useful! I’d be happy to accept a pr if you can put one together
