### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by sugarfree1** [fcheung/asset_symlink#3]
Hi there,
Is there any chance that version for Rails 5 will be released?
Thanks in advance

**Comment by fcheung** [comment]
Hi,

I haven't tried it under rails 5 - the version constraint in the gemspec is more there out of paranoia than anything else. Have you tried it with rails 5?

**Comment by fcheung** [comment]
Master should work with rails 5

**Comment by sugarfree1** [comment]
Thank you!
